export const Robots =[
    {
        id:1,
        name:'Ashish',
        user:'Ak',
        email:'AK.b@gmail.com'
    },
    {
        id:1,
        name:'kamlesh',
        user:'kb',
        email:'kb@gmail.com'
    },
    {
        id:2,
        name:'chatur ram',
        user:'cr',
        email:'crb@gmail.com'
    },
    {
        id:3,
        name:'manula',
        user:'mb',
        email:'mb@gmail.com'
    },
    {
        id:4,
        name:'chhotu',
        user:'c',
        email:'c@gmail.com'
    },
    {
        id:5,
        name:'harish',
        user:'h',
        email:'h@gmail.com'
    },
    {
        id:6,
        name:'Rahul',
        user:'R',
        email:'R@gmail.com'
    },
    {
        id:7,
        name:'Bhupal',
        user:'B',
        email:'B@gmail.com'
    },
    {
        id:8,
        name:'Devendra',
        user:'D',
        email:'D@gmail.com'
    },
    {
        id:9,
        name:'Europ',
        user:'E',
        email:'E@gmail.com'
    },
    {
        id:10,
        name:'fuddu',
        user:'f',
        email:'f@gmail.com'
    },
]